### ISSUE TITLE
gcc missing

### ISSUE THREAD

**Issue by plaindocs** [perryk/perryk-vagrant-osticket#1]
Heya,

I get a GCC related error in the daemonize stage:

```
TASK [geerlingguy.daemonize : Build daemonize.] ********************************
failed: [default] (item=./configure --prefix=/usr) => {"changed": true, "cmd": ["./configure", "--prefix=/usr"], "delta": "0:00:00.139460", "end": "2019-04-07 09:15:54.209315", "item": "./configure --prefix=/usr", "msg": "non-zero return code", "rc": 1, "start": "2019-04-07 09:15:54.069855", "stderr": "configure: error: in `/root/daemonize-release-1.7.7':\nconfigure: error: no acceptable C compiler found in $PATH\nSee `config.log' for more details", "stderr_lines": ["configure: error: in `/root/daemonize-release-1.7.7':", "configure: error: no acceptable C compiler found in $PATH", "See `config.log' for more details"], "stdout": "checking for gcc... no\nchecking for cc... no\nchecking for cl.exe... no", "stdout_lines": ["checking for gcc... no", "checking for cc... no", "checking for cl.exe... no"]}
failed: [default] (item=make) => {"changed": true, "cmd": ["make"], "delta": "0:00:00.011770", "end": "2019-04-07 09:15:54.571838", "item": "make", "msg": "non-zero return code", "rc": 2, "start": "2019-04-07 09:15:54.560068", "stderr": "make: *** No targets specified and no makefile found.  Stop.", "stderr_lines": ["make: *** No targets specified and no makefile found.  Stop."], "stdout": "", "stdout_lines": []}
failed: [default] (item=make install) => {"changed": true, "cmd": ["make", "install"], "delta": "0:00:00.005640", "end": "2019-04-07 09:15:54.904141", "item": "make install", "msg": "non-zero return code", "rc": 2, "start": "2019-04-07 09:15:54.898501", "stderr": "make: *** No rule to make target `install'.  Stop.", "stderr_lines": ["make: *** No rule to make target `install'.  Stop."], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/ZZZZZZ/perryk-vagrant-osticket/playbook.retry

```

Fixed by sshing in and installing gcc

```
TASK [geerlingguy.daemonize : Build daemonize.] ********************************
changed: [default] => (item=./configure --prefix=/usr)
changed: [default] => (item=make)
changed: [default] => (item=make install)
```

**Comment by perryk** [comment]
Thanks for the heads up on this. 

I hadn't noticed this before but it does look to be expected behaviour from the geerlingguy.daemonize role: https://github.com/geerlingguy/ansible-role-daemonize#requirements

I'll modify the playbook.yml at the top level which is what Vagrant calls and make it so that it installs the perryk.osticket.provision.dev role before geerlingguy.mailhog role.

Mailhog is only useful if you want to test out sending of emails from osTicket and you want to capture and inspect the emails rather than actually sending them. 

I found Mailhog handy when I was creating email templates, however, for the most part during testing email isn't a big concern and I likely had the Mailhog role turned off.

Generally speaking, this role designed for testing/development purposes only.

Cheers.

**Comment by plaindocs** [comment]
Thanks

Yeah, I'm actually only trying to use it to checkout the features without installing everything from scratch. 

If you have a list of stuff I can comment out to make that easy, even better.

**Comment by perryk** [comment]
All good, everything should be working now except for the 2 of the plugins. All the other plugins are still in place.

Try a git pull to update this repo or download it again to pick up the changes.

Once you have completed a `vagrant up` or `vagrant up --provision` you should be able to reach the website running on the vagrant VM and complete the setup form using your own name and email addresses then enter the database details from the roles/perryk.osticket.provision.dev/vars/main.yml file.

Once setup is complete you can run `./vagrant_osticket_remove_setup.sh` to fix permissions and prevent further access to the setup section.

You still need to do things like configure email accounts for checking, activating and configuring of plugins, as well as changing any other settings you want to use.

Also this setup is still using version 1.10 currently, rather than the current version of 1.11 which improves the viewing and customising of queues. If you want to try out 1.11 just say and I'll explain how to do so as there has been some good changes in that version.

Whilst you may no need it for evaluating osTicket, the extra script for modifying the source can be run with `./vagrant_osticket_modify_source.sh` .  This fixes a bunch of stuff and improves the behaviour of others. n.b that this extra script only works for 1.10 currently.

Feel free to ask me questions, you will receive plenty of help from the forums and the main osTicket github too. https://forum.osticket.com/

Cheers.

**Comment by perryk** [comment]
reorder of roles has this sorted out.
